version: "3"
   
services:

  app:
    image: vrekshta/app:${version}
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./app/.env
        target: /.env

  docs:
    image: vrekshta/docs:${version}

  db:
    image: postgres:13-alpine
    volumes:
      - app_db_vol:/var/lib/postgresql/data
      - ./assets/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_DB=testapp_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

volumes:
  app_db_vol:

