name: build

on:
  push:
    tags:
      - v*
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [ "golangci-lint", "test" ]
    types:
      - completed

defaults:
  run:
    working-directory: ./app
    
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: testapp_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:         
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
          
      - name: Create DB schema
        run: |
          psql -h postgres -U postgres -h localhost -d testapp_db < ../assets/schema.sql
        env:
          PGPASSWORD: postgres
          
      - name: Run tests
        run: |
          go test -v

          
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        
      - name: Build app
        run: go build -v
      
      
      
